### ISSUE TITLE
Update PyPI index

### ISSUE THREAD

**Issue by shnewto** [tarruda/python-autopxd#14]
I'd like to be able to use `pip` to install your module instead of downloading the source but the most current version available is out of date with the state of this repository and the last couple changes are valuable to me. 

Thanks!

**Comment by gabrieldemarmiesse** [comment]
Hi, I know it's old, but I made a fork of this repo and uploaded it to PyPI so you can pip install the up-to-date package now. 

https://github.com/gabrieldemarmiesse/python-autopxd2

**Comment by shnewto** [comment]
@gabrieldemarmiesse that's fantastic thanks!
